// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: back-end/proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DivisionDuration float32 `protobuf:"fixed32,1,opt,name=divisionDuration,proto3" json:"divisionDuration,omitempty"`
	AddDuration      float32 `protobuf:"fixed32,2,opt,name=addDuration,proto3" json:"addDuration,omitempty"`
	MultiplyDuration float32 `protobuf:"fixed32,3,opt,name=multiplyDuration,proto3" json:"multiplyDuration,omitempty"`
	SubtractDuration float32 `protobuf:"fixed32,4,opt,name=subtractDuration,proto3" json:"subtractDuration,omitempty"`
}

func (x *AgentSettings) Reset() {
	*x = AgentSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_back_end_proto_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSettings) ProtoMessage() {}

func (x *AgentSettings) ProtoReflect() protoreflect.Message {
	mi := &file_back_end_proto_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSettings.ProtoReflect.Descriptor instead.
func (*AgentSettings) Descriptor() ([]byte, []int) {
	return file_back_end_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentSettings) GetDivisionDuration() float32 {
	if x != nil {
		return x.DivisionDuration
	}
	return 0
}

func (x *AgentSettings) GetAddDuration() float32 {
	if x != nil {
		return x.AddDuration
	}
	return 0
}

func (x *AgentSettings) GetMultiplyDuration() float32 {
	if x != nil {
		return x.MultiplyDuration
	}
	return 0
}

func (x *AgentSettings) GetSubtractDuration() float32 {
	if x != nil {
		return x.SubtractDuration
	}
	return 0
}

type AgentInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AgentInfoRequest) Reset() {
	*x = AgentInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_back_end_proto_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfoRequest) ProtoMessage() {}

func (x *AgentInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_back_end_proto_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfoRequest.ProtoReflect.Descriptor instead.
func (*AgentInfoRequest) Descriptor() ([]byte, []int) {
	return file_back_end_proto_agent_proto_rawDescGZIP(), []int{1}
}

type AgentInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AgentID        int32          `protobuf:"varint,2,opt,name=agentID,proto3" json:"agentID,omitempty"`
	CompletedTasks uint32         `protobuf:"varint,3,opt,name=completedTasks,proto3" json:"completedTasks,omitempty"`
	LastTaskID     uint32         `protobuf:"varint,4,opt,name=lastTaskID,proto3" json:"lastTaskID,omitempty"`
	Settings       *AgentSettings `protobuf:"bytes,5,opt,name=settings,proto3" json:"settings,omitempty"`
}

func (x *AgentInfoResponse) Reset() {
	*x = AgentInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_back_end_proto_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfoResponse) ProtoMessage() {}

func (x *AgentInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_back_end_proto_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfoResponse.ProtoReflect.Descriptor instead.
func (*AgentInfoResponse) Descriptor() ([]byte, []int) {
	return file_back_end_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentInfoResponse) GetAgentID() int32 {
	if x != nil {
		return x.AgentID
	}
	return 0
}

func (x *AgentInfoResponse) GetCompletedTasks() uint32 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

func (x *AgentInfoResponse) GetLastTaskID() uint32 {
	if x != nil {
		return x.LastTaskID
	}
	return 0
}

func (x *AgentInfoResponse) GetSettings() *AgentSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SetAgentSettingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Settings *AgentSettings `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
}

func (x *SetAgentSettingsRequest) Reset() {
	*x = SetAgentSettingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_back_end_proto_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAgentSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAgentSettingsRequest) ProtoMessage() {}

func (x *SetAgentSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_back_end_proto_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAgentSettingsRequest.ProtoReflect.Descriptor instead.
func (*SetAgentSettingsRequest) Descriptor() ([]byte, []int) {
	return file_back_end_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *SetAgentSettingsRequest) GetSettings() *AgentSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SetAgentSettingsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetAgentSettingsResponse) Reset() {
	*x = SetAgentSettingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_back_end_proto_agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAgentSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAgentSettingsResponse) ProtoMessage() {}

func (x *SetAgentSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_back_end_proto_agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAgentSettingsResponse.ProtoReflect.Descriptor instead.
func (*SetAgentSettingsResponse) Descriptor() ([]byte, []int) {
	return file_back_end_proto_agent_proto_rawDescGZIP(), []int{4}
}

var File_back_end_proto_agent_proto protoreflect.FileDescriptor

var file_back_end_proto_agent_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x62, 0x61, 0x63, 0x6b, 0x2d, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x73, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xb5,
	0x01, 0x0a, 0x0d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x12, 0x2a, 0x0a, 0x10, 0x64, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x10, 0x64, 0x69, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b,
	0x61, 0x64, 0x64, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0b, 0x61, 0x64, 0x64, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a,
	0x0a, 0x10, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x10, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x6c, 0x79, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x75,
	0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x10, 0x73, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x44, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x12, 0x0a, 0x10, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xc6, 0x01, 0x0a, 0x11, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x26,
	0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x54, 0x61,
	0x73, 0x6b, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74,
	0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x12, 0x3b, 0x0a, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x73, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x22, 0x56, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b,
	0x0a, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x1a, 0x0a, 0x18, 0x53,
	0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xc5, 0x01, 0x0a, 0x09, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x47, 0x52, 0x50, 0x43, 0x12, 0x52, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x22, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x0b, 0x53, 0x65, 0x74,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x29, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x73, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x6f,
	0x6e, 0x74, 0x79, 0x31, 0x31, 0x31, 0x2f, 0x53, 0x75, 0x70, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x2d, 0x65, 0x6e, 0x64, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_back_end_proto_agent_proto_rawDescOnce sync.Once
	file_back_end_proto_agent_proto_rawDescData = file_back_end_proto_agent_proto_rawDesc
)

func file_back_end_proto_agent_proto_rawDescGZIP() []byte {
	file_back_end_proto_agent_proto_rawDescOnce.Do(func() {
		file_back_end_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_back_end_proto_agent_proto_rawDescData)
	})
	return file_back_end_proto_agent_proto_rawDescData
}

var file_back_end_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_back_end_proto_agent_proto_goTypes = []interface{}{
	(*AgentSettings)(nil),            // 0: agents_managment.AgentSettings
	(*AgentInfoRequest)(nil),         // 1: agents_managment.AgentInfoRequest
	(*AgentInfoResponse)(nil),        // 2: agents_managment.AgentInfoResponse
	(*SetAgentSettingsRequest)(nil),  // 3: agents_managment.SetAgentSettingsRequest
	(*SetAgentSettingsResponse)(nil), // 4: agents_managment.SetAgentSettingsResponse
}
var file_back_end_proto_agent_proto_depIdxs = []int32{
	0, // 0: agents_managment.AgentInfoResponse.settings:type_name -> agents_managment.AgentSettings
	0, // 1: agents_managment.SetAgentSettingsRequest.settings:type_name -> agents_managment.AgentSettings
	1, // 2: agents_managment.AgentGRPC.GetInfo:input_type -> agents_managment.AgentInfoRequest
	3, // 3: agents_managment.AgentGRPC.SetSettings:input_type -> agents_managment.SetAgentSettingsRequest
	2, // 4: agents_managment.AgentGRPC.GetInfo:output_type -> agents_managment.AgentInfoResponse
	4, // 5: agents_managment.AgentGRPC.SetSettings:output_type -> agents_managment.SetAgentSettingsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_back_end_proto_agent_proto_init() }
func file_back_end_proto_agent_proto_init() {
	if File_back_end_proto_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_back_end_proto_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_back_end_proto_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_back_end_proto_agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_back_end_proto_agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAgentSettingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_back_end_proto_agent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAgentSettingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_back_end_proto_agent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_back_end_proto_agent_proto_goTypes,
		DependencyIndexes: file_back_end_proto_agent_proto_depIdxs,
		MessageInfos:      file_back_end_proto_agent_proto_msgTypes,
	}.Build()
	File_back_end_proto_agent_proto = out.File
	file_back_end_proto_agent_proto_rawDesc = nil
	file_back_end_proto_agent_proto_goTypes = nil
	file_back_end_proto_agent_proto_depIdxs = nil
}
