definitions:
  github_com_xplago-edu_drem-file-service_internal_app_build.Info:
    properties:
      arch:
        type: string
      build_date:
        type: string
      commit_hash:
        type: string
      compiler:
        type: string
      go_version:
        type: string
      os:
        type: string
      version:
        type: string
    type: object
  internal_gateways_web_controllers_apiv1_status.Response:
    properties:
      build:
        $ref: '#/definitions/github_com_xplago-edu_drem-file-service_internal_app_build.Info'
      id:
        type: string
      status:
        type: string
    type: object
  internal_gateways_web_controllers_apiv1_status.ResponseDoc:
    properties:
      data:
        properties:
          attributes:
            $ref: '#/definitions/internal_gateways_web_controllers_apiv1_status.Response'
        type: object
    type: object
info:
  contact: {}
paths:
  /api/v1/download:
    get:
      consumes:
      - application/json
      description: download file from a database
      operationId: download-file
      produces:
      - application/json
      responses: {}
      summary: Download File
  /api/v1/status:
    get:
      consumes:
      - application/json
      description: get status
      operationId: get-status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_gateways_web_controllers_apiv1_status.ResponseDoc'
      summary: Get Application Status
  /api/v1/upload:
    post:
      consumes:
      - application/json
      description: upload file into a database
      operationId: upload-file
      produces:
      - application/json
      responses: {}
      summary: Upload File
swagger: "2.0"
